### PR TITLE
Week 15 - Project todos, Isabella Markskog

### PR DESCRIPTION
**Pull request by IsabellaM5**
**Link to my deployed project**
https://tender-blackwell-c83127.netlify.app/ 

**My reflections on how this week's project turned out**
I did all the blue level requirements and some red and black level requirements (clear all button, used styled components, added a datepicker).

This week's project was great fun! The difficult part of this week's assignment was to just decide what features I wanted to add - other than the ones that are part of the blue level requirements 😅 I felt it was challenging to just stick to my initial plan and I found myself from time to time researching about a feature I wanted to add (usually when I saw someone in the team talking about a feature they had implemented in their project). This is definitely a project I'll have to get back to and touch up on (which you can tell by viewing my README file on what I would do if I had more time haha).   

**Things I'd like to have clarified or explained in more detail**
Nothing at the moment actually, I think the assignment was pretty straightforward. I look forward to learning more about Redux, the Redux store and how to work with Redux in React. 👍

### CODE REVIEW

**Review by idasylven — APPROVED** [review]
What can I simply say more than...WOW! Your project is OUTSTANDING! 🤩 
Yep, Blue Level requirements are met without a doubt, and with superb Red and Black Level add-ons 🔵 🔴 ⚫  

The user experience is great! All features are really straight forward - I think the color scheme (very soothing and easy on the eye btw 👁️ , well suited for when you are stressed about all your "To Do's" 😅 ), the empty state image, button design and icon implementation are fantastic 🐅  The strikethrough mark over the text when a task is marked as checked is a very nice visual, and the date picker and edit option awesome functionalities 📅  ✍🏻

I also love how reflective you are around your projects, both in the README section and with your comments in the Pull Request. Me reviewing the actual code probably has more in in for me, than what it has for you (so thank you for being an inspiration 🌟 ) I have no remarks here - it is neat, well structured, easy to follow and with clear and consistent naming 🧘🏻  

I can see that you have ambition for more (and I know you can do it without a doubt), but regardless - this is really professional and thorough work! 👌🏼 🎉  💪🏻

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
This app is nearly perfect 🦄 I love how it looks and performs but you forgot to create a task counter which is needed to meet the blue level requirements.

**Comment by IsabellaM5** [comment]
Hi Karol! 

I have a counter implemented. If you check my component TodoList.js on line 92. Also see below pic of how the counter looks in my application after a todo has been added. 

image

**Comment by IsabellaM5** [comment]
@KarolCislowski 

Please see above message :)

**Review by KarolCislowski — APPROVED** [review]
I need to think to start wearing glasses 🤓 
Great work 🥳

**Pull request closed without merging**
