### PR TITLE
To Do List ✅

### PR DESCRIPTION
**Pull request by destinyleia**
Link to my deployed project:

Deploying my site = failed 😞 

My reflections on how this week's project turned out:
I still need to practice how it all works together, but it’s just practice :)

Things I'd like to have clarified or explained in more detail:
How it all works together!

### CODE REVIEW

**Review by HIPPIEKICK — CHANGES_REQUESTED** [review]
Prevent the user from submitting empty todos!

**Comment by destinyleia** [comment]
How do I do that? :)

**Comment by HIPPIEKICK** [comment]
> How do I do that? :)

You can use the `required` attribute or validate in some other way so that the value is not empty before submitting :)

**Comment by destinyleia** [comment]
> > How do I do that? :)
> 
> You can use the `required` attribute or validate in some other way so that the value is not empty before submitting :)

thank you! Think I solved it :)

**Review by HIPPIEKICK — APPROVED** [review]

**Pull request closed without merging**
